/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralFrame.java
 *
 * Created on 26-nov-2008, 0:25:11
 */

package presentacion;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.JPanel;
import presentacion.buscador.BuscadorPanel;
import presentacion.buscador.GUIBuscador;
import presentacion.configuracion.GUIConfiguracion;
import presentacion.descargas.GUIDescargas;
import presentacion.servidores.GUIServidores;

/**
 *
 * @author Victor
 */
public class GeneralFrame extends javax.swing.JFrame {
    private JPanel panelActual;

    /** Creates new form GeneralFrame */
    public GeneralFrame() {
        
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        setVisible(true);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bServidores = new javax.swing.JButton();
        bConectar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bTrafico = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bConfiguracion = new javax.swing.JButton();
        bEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(GeneralFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setName("Form"); // NOI18N

        bServidores.setFont(resourceMap.getFont("Form.font")); // NOI18N
        bServidores.setText(resourceMap.getString("bServidores.text")); // NOI18N
        bServidores.setMaximumSize(new java.awt.Dimension(83, 23));
        bServidores.setMinimumSize(new java.awt.Dimension(83, 23));
        bServidores.setName("bServidores"); // NOI18N
        bServidores.setPreferredSize(new java.awt.Dimension(83, 23));
        bServidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarServidores(evt);
            }
        });

        bConectar.setFont(resourceMap.getFont("Form.font")); // NOI18N
        bConectar.setText(resourceMap.getString("bConectar.text")); // NOI18N
        bConectar.setMaximumSize(new java.awt.Dimension(83, 23));
        bConectar.setMinimumSize(new java.awt.Dimension(83, 23));
        bConectar.setName("bConectar"); // NOI18N
        bConectar.setPreferredSize(new java.awt.Dimension(83, 23));
        bConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bConectarcargarServidores(evt);
            }
        });

        bBuscar.setFont(resourceMap.getFont("Form.font")); // NOI18N
        bBuscar.setLabel(resourceMap.getString("bBuscar.label")); // NOI18N
        bBuscar.setMaximumSize(new java.awt.Dimension(83, 23));
        bBuscar.setMinimumSize(new java.awt.Dimension(83, 23));
        bBuscar.setName("bBuscar"); // NOI18N
        bBuscar.setPreferredSize(new java.awt.Dimension(83, 23));
        bBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarBuscador(evt);
            }
        });

        bTrafico.setFont(resourceMap.getFont("Form.font")); // NOI18N
        bTrafico.setText(resourceMap.getString("bTrafico.text")); // NOI18N
        bTrafico.setMaximumSize(new java.awt.Dimension(83, 23));
        bTrafico.setMinimumSize(new java.awt.Dimension(83, 23));
        bTrafico.setName("bTrafico"); // NOI18N
        bTrafico.setPreferredSize(new java.awt.Dimension(83, 23));
        bTrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarTrafico(evt);
            }
        });

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        jSeparator1.setName("jSeparator1"); // NOI18N

        bConfiguracion.setFont(resourceMap.getFont("Form.font")); // NOI18N
        bConfiguracion.setText(resourceMap.getString("bConfiguracion.text")); // NOI18N
        bConfiguracion.setMaximumSize(new java.awt.Dimension(83, 23));
        bConfiguracion.setMinimumSize(new java.awt.Dimension(83, 23));
        bConfiguracion.setName("bConfiguracion"); // NOI18N
        bConfiguracion.setPreferredSize(new java.awt.Dimension(83, 23));
        bConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarConfiguracion(evt);
            }
        });

        bEstadisticas.setFont(resourceMap.getFont("Form.font")); // NOI18N
        bEstadisticas.setText(resourceMap.getString("bEstadisticas.text")); // NOI18N
        bEstadisticas.setMaximumSize(new java.awt.Dimension(83, 23));
        bEstadisticas.setMinimumSize(new java.awt.Dimension(83, 23));
        bEstadisticas.setName("bEstadisticas"); // NOI18N
        bEstadisticas.setPreferredSize(new java.awt.Dimension(83, 23));
        bEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarEstadisticas(evt);
            }
        });

        mainPanel.add( "Servidores", GUIServidores.instancia().getPanel());
        mainPanel.add( "Buscador", GUIBuscador.instancia().getPanel());
        mainPanel.add( "Configuracion", GUIConfiguracion.instancia().getPanel());
        mainPanel.add( "Descargas", GUIDescargas.instancia().getPanel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bServidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bServidores, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bTrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarServidores(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarServidores

       ((CardLayout)mainPanel.getLayout()).show( mainPanel,"Servidores" );
       
}//GEN-LAST:event_cargarServidores

    private void bConectarcargarServidores(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConectarcargarServidores
        // TODO add your handling code here:
}//GEN-LAST:event_bConectarcargarServidores

    private void cargarBuscador(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarBuscador
       
        ((CardLayout)mainPanel.getLayout()).show( mainPanel,"Buscador" );
        
}//GEN-LAST:event_cargarBuscador

    private void cargarTrafico(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarTrafico
        ((CardLayout)mainPanel.getLayout()).show( mainPanel,"Descargas" );
}//GEN-LAST:event_cargarTrafico

    private void cargarConfiguracion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarConfiguracion
        ((CardLayout)mainPanel.getLayout()).show( mainPanel,"Configuracion" );
}//GEN-LAST:event_cargarConfiguracion

    private void cargarEstadisticas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarEstadisticas
        // TODO add your handling code here:
}//GEN-LAST:event_cargarEstadisticas

    // Recoge el evento de actualización
    public Image getIconImage() {
		
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(GeneralFrame.class);

        return resourceMap.getImageIcon("imageLabel.icon").getImage();
	}
    
    // Recoge el evento de actualización
	public void update(int evento, Object params) {
		switch (evento) {
			case GUIGeneral.MOSTRAR_MENU:
				setVisible(true);
				break;
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bConfiguracion;
    private javax.swing.JButton bEstadisticas;
    private javax.swing.JButton bServidores;
    private javax.swing.JButton bTrafico;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
